version: "3.9"
services:
  bookstoredb:
    image: postgres
    container_name: bookstore_db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - postgres_bookstore_db
    ports:
      - 5432:5432
    volumes:
      - .docker/pgdata:/var/lib/postgresql/data

  prometheus_service:

networks:
  postgres_bookstore_db:
    driver: bridge

volumes:
  pgdata:
