global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
- job_name: myapp
  metrics_path: /metrics
  static_configs:
    - targets: ["bookstoreapp:3001", "localhost:9090"]

